// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebShop.Dal.Context;

namespace WebShop.Dal.Migrations
{
    [DbContext(typeof(WebShopDbContext))]
    [Migration("20200528085835_last_one")]
    partial class last_one
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("WebShop.Dal.Models.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CommentText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("WebShop.Dal.Models.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Available")
                        .HasColumnType("int");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateSinceInStore")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DiscountedPrice")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("GamingFlag")
                        .HasColumnType("bit");

                    b.Property<bool>("HasRGB")
                        .HasColumnType("bit");

                    b.Property<bool>("HighlightedItem")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OriginalPrice")
                        .HasColumnType("int");

                    b.Property<string>("PicturePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Warranty")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Items");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Item");
                });

            modelBuilder.Entity("WebShop.Dal.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("int");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("WebShop.Dal.Models.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("WebShop.Dal.Models.Rating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.Property<Guid?>("WebShopUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasAlternateKey("ItemId", "UserId");

                    b.HasIndex("WebShopUserId");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("WebShop.Dal.Models.UserSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("WebShopUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WebShopUserId");

                    b.ToTable("UserSubscriptions");
                });

            modelBuilder.Entity("WebShop.Dal.Models.Users.UserCartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("UserId");

                    b.ToTable("UserCartItems");
                });

            modelBuilder.Entity("WebShop.Dal.Models.WebShopUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NickName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("WebShop.Dal.Models.Case", b =>
                {
                    b.HasBaseType("WebShop.Dal.Models.Item");

                    b.Property<int>("BuiltInFanNumber")
                        .HasColumnType("int");

                    b.Property<int>("Depth")
                        .HasColumnType("int");

                    b.Property<int>("HDDNumber")
                        .HasColumnType("int");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<int>("SupportedMotherboard")
                        .HasColumnType("int");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Case");

                    b.HasData(
                        new
                        {
                            Id = new Guid("21000000-0000-0000-0000-000000000000"),
                            Available = 10,
                            Category = 2,
                            DateSinceInStore = new DateTime(2020, 4, 8, 10, 58, 34, 386, DateTimeKind.Local).AddTicks(3778),
                            Description = "E-ATX formátumú Torony kialakítású számtógépház beépített 2 db 140 mm-es ventilátorral. Letisztul formabontó design, Edzett üveg oldalpanelek, TT LCS tanúsítvány. ",
                            GamingFlag = false,
                            HasRGB = false,
                            HighlightedItem = false,
                            IsUsed = false,
                            Manufacturer = "Thermaltake",
                            Name = "Thermaltake CA-1P6-00F1WN-00 Level 20 HT számítógépház fekete",
                            OriginalPrice = 59000,
                            PicturePath = "21000000-0000-0000-0000-000000000000.jpg",
                            ShortDescription = "Very nice case",
                            Warranty = "3 years",
                            BuiltInFanNumber = 3,
                            Depth = 503,
                            HDDNumber = 4,
                            Height = 613,
                            SupportedMotherboard = 0,
                            Width = 468
                        },
                        new
                        {
                            Id = new Guid("22000000-0000-0000-0000-000000000000"),
                            Available = 10,
                            Category = 2,
                            DateSinceInStore = new DateTime(2020, 4, 8, 10, 58, 34, 388, DateTimeKind.Local).AddTicks(1704),
                            Description = "Morbi efficitur iaculis luctus. Quisque efficitur magna nec sapien finibus euismod. Nullam suscipit enim id dui hendrerit imperdiet. Donec ultrices venenatis nisl, nec condimentum neque.",
                            GamingFlag = false,
                            HasRGB = false,
                            HighlightedItem = false,
                            IsUsed = false,
                            Manufacturer = "DeepCool",
                            Name = "DeepCool EARLKASE RGB WH fehér számítógép ház",
                            OriginalPrice = 59000,
                            PicturePath = "22000000-0000-0000-0000-000000000000.jpg",
                            ShortDescription = "White and big case",
                            Warranty = "3 years",
                            BuiltInFanNumber = 3,
                            Depth = 500,
                            HDDNumber = 4,
                            Height = 511,
                            SupportedMotherboard = 0,
                            Width = 204
                        },
                        new
                        {
                            Id = new Guid("31000000-0000-0000-0000-000000000000"),
                            Available = 2,
                            Category = 2,
                            DateSinceInStore = new DateTime(2020, 4, 8, 10, 58, 34, 388, DateTimeKind.Local).AddTicks(1788),
                            Description = "A Thermaltake a számítógépházába összeolvasztotta a szépséget és a teljesítményt, a View 32 Tempered Glass RGB Edition középkategóriás számítógépház tervezésébe. Négy prémium minőségű, 4 mm vastag, edzett üvegablakkal (felső, elülső, bal és jobb) készült, a belső rendszer közvetlen megtekintéséhez és a kiváló alvázvédelemhez. Három beépített 120 mm-es Riing LED RGB ventilátor (kettő elöl és egy hátul) biztosítja az RGB megvilágítását és az optimális szellőzést.",
                            DiscountedPrice = 18000,
                            GamingFlag = false,
                            HasRGB = false,
                            HighlightedItem = true,
                            IsUsed = false,
                            Manufacturer = "Thermaltake",
                            Name = "Thermaltake View 32 Tempered Glass RGB Edition",
                            OriginalPrice = 49000,
                            PicturePath = "31000000-0000-0000-0000-000000000000.jpg",
                            ShortDescription = "So much RGB => So much FPS",
                            Warranty = "3 years",
                            BuiltInFanNumber = 3,
                            Depth = 500,
                            HDDNumber = 4,
                            Height = 521,
                            SupportedMotherboard = 0,
                            Width = 201
                        });
                });

            modelBuilder.Entity("WebShop.Dal.Models.CompletPC", b =>
                {
                    b.HasBaseType("WebShop.Dal.Models.Item");

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Case")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cpu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Drives")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gpu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Memories")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Motherboard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PowerSupply")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("CompletPC");

                    b.HasData(
                        new
                        {
                            Id = new Guid("21000000-0000-0000-0000-000000000011"),
                            Available = 15,
                            Category = 8,
                            DateSinceInStore = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A dinamikus, szélnyíró készülékház kifinomult formával rendelkezik, hogy növelje a légáramot, miközben 30dB alatt tartja a zajszinteket a csendesebb játék és munka érdekében. Az elülső hangsúlyokon keresztül megtalálható vágások kiszélesítették a szellőzőket, így több levegő jut a készülékházba. Belül a CPU, a grafikus kártya és a tápegység külön foglalatokban található, minimalizálva a termikus interferenciát és csökkentve a környezeti hőmérsékletet. A légáram növelő dizájn felgyorsítja a hőeloszlást, hogy magasabb általános teljesítményt tegyen lehetővé és tartson meg.",
                            GamingFlag = true,
                            HasRGB = true,
                            HighlightedItem = false,
                            IsUsed = false,
                            Manufacturer = "ASUS",
                            Name = "ASUS ROG asztali gamer számítógép (G15DH-HU011D)",
                            OriginalPrice = 595790,
                            PicturePath = "21000000-0000-0000-0000-000000000011.jpg",
                            ShortDescription = "Viszonylag olcsó, jó árérték arányú számítógép",
                            Warranty = "2 years",
                            Case = "Asus omega colorful RGB gépház",
                            Cpu = "AMD Ryzen 5 3600X",
                            Drives = "256GB SSD, 1TB HDD",
                            Gpu = "nvidia geforce gtx 1650",
                            Memories = "2 x Kingston HyperX fury 8gb 3200mhz",
                            Motherboard = "ASUS Strix B460 gaming pro alaplap"
                        },
                        new
                        {
                            Id = new Guid("21000000-0000-0000-0000-000000000012"),
                            Available = 3,
                            Category = 8,
                            DateSinceInStore = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "A dinamikus, szélnyíró készülékház kifinomult formával rendelkezik, hogy növelje a légáramot, miközben 30dB alatt tartja a zajszinteket a csendesebb játék és munka érdekében. Az elülső hangsúlyokon keresztül megtalálható vágások kiszélesítették a szellőzőket, így több levegő jut a készülékházba. Belül a CPU, a grafikus kártya és a tápegység külön foglalatokban található, minimalizálva a termikus interferenciát és csökkentve a környezeti hőmérsékletet. A légáram növelő dizájn felgyorsítja a hőeloszlást, hogy magasabb általános teljesítményt tegyen lehetővé és tartson meg.",
                            GamingFlag = false,
                            HasRGB = false,
                            HighlightedItem = false,
                            IsUsed = false,
                            Manufacturer = "ASUS",
                            Name = "ASUS ROG Strix GA15 Gamer asztali számítógép(G15DH-HU004D)",
                            OriginalPrice = 295790,
                            PicturePath = "21000000-0000-0000-0000-000000000012.jpg",
                            ShortDescription = "Highend gaming pc mindenre is",
                            Warranty = "3 years",
                            Case = "Asus Strix Boss gépház",
                            Cpu = "Intel I9-9900K",
                            Drives = "1TGB SSD, 10TB HDD",
                            Gpu = "nVidia GeForce RTX 2060 Super - 8GB",
                            Memories = "4 x Kingston HyperX fury 8gb 3200mhz",
                            Motherboard = "ASUS Strix Z490 gaming pro alaplap"
                        });
                });

            modelBuilder.Entity("WebShop.Dal.Models.Hardware", b =>
                {
                    b.HasBaseType("WebShop.Dal.Models.Item");

                    b.Property<int>("BaseClock")
                        .HasColumnType("int");

                    b.Property<int>("TDP")
                        .HasColumnType("int");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Hardware");
                });

            modelBuilder.Entity("WebShop.Dal.Models.Cpu", b =>
                {
                    b.HasBaseType("WebShop.Dal.Models.Hardware");

                    b.Property<int>("CoreNumber")
                        .HasColumnType("int");

                    b.Property<string>("ProcessorFamily")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Socket")
                        .HasColumnType("int");

                    b.Property<int>("Technology")
                        .HasColumnType("int");

                    b.Property<int>("ThreadNumber")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Cpu");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000000"),
                            Available = 10,
                            Category = 0,
                            DateSinceInStore = new DateTime(2020, 4, 8, 10, 58, 34, 388, DateTimeKind.Local).AddTicks(4801),
                            Description = "A legjobb többprocesszoros teljesítmény az osztályában, a játékosok számára. Jobb teljesítmény. Hihetetlen technológia. Az intelligens Ryzen processzorok csak még okosabbak lettek. ",
                            GamingFlag = false,
                            HasRGB = false,
                            HighlightedItem = false,
                            IsUsed = false,
                            Manufacturer = "AMD",
                            Name = "AMD Ryzen 3 2200G",
                            OriginalPrice = 31500,
                            PicturePath = "10000000-0000-0000-0000-000000000000.jpg",
                            ShortDescription = "So basic processor",
                            Warranty = "5 years",
                            BaseClock = 3400,
                            TDP = 65,
                            Weight = 0,
                            CoreNumber = 4,
                            ProcessorFamily = "AMD Ryzen 3",
                            Socket = 3,
                            Technology = 14,
                            ThreadNumber = 4
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000000"),
                            Available = 10,
                            Category = 0,
                            DateSinceInStore = new DateTime(2020, 4, 28, 10, 58, 34, 388, DateTimeKind.Local).AddTicks(4902),
                            Description = "Magok száma:6, Processzor foglalat:Intel 1151 v2, Család:Coffee Lake, Órajel (Mhz):3700, VGA típus:Intel UHD Graphics 630, Hűtőventilátor:Nem, Fogyasztás (W):95, Architektúra (bit):64, L3 Cache (MB):9, Hűtőborda:Nem, Gyártási technológia (nm):14, L2 Cache (MB):2, Szálak száma:6,",
                            DiscountedPrice = 65000,
                            GamingFlag = false,
                            HasRGB = false,
                            HighlightedItem = true,
                            IsUsed = false,
                            Manufacturer = "Intel",
                            Name = "Intel Core i5-9600K",
                            OriginalPrice = 82000,
                            PicturePath = "20000000-0000-0000-0000-000000000000.jpg",
                            ShortDescription = "Very good gaming processor",
                            Warranty = "3 years",
                            BaseClock = 3700,
                            TDP = 65,
                            Weight = 0,
                            CoreNumber = 6,
                            ProcessorFamily = "Intel core 5",
                            Socket = 10,
                            Technology = 14,
                            ThreadNumber = 6
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000000"),
                            Available = 10,
                            Category = 0,
                            DateSinceInStore = new DateTime(2020, 4, 28, 10, 58, 34, 388, DateTimeKind.Local).AddTicks(4911),
                            Description = "Magok száma:6, Processzor foglalat:Intel 1151 v2, Család:Coffee Lake, Órajel (Mhz):2900, VGA típus:Nem, Hűtőventilátor:Igen, Fogyasztás (W):65, Architektúra (bit):64, L3 Cache (MB):9, Hűtőborda:Igen, Gyártási technológia (nm):14, L2 Cache (MB):1,5, Szálak száma:6,",
                            GamingFlag = false,
                            HasRGB = false,
                            HighlightedItem = false,
                            IsUsed = false,
                            Manufacturer = "Intel",
                            Name = "Intel Core i5-9400f",
                            OriginalPrice = 82000,
                            PicturePath = "30000000-0000-0000-0000-000000000000.jpg",
                            ShortDescription = "Középkategóriás processor munkára és játékra egyaránt",
                            Warranty = "3 years",
                            BaseClock = 3500,
                            TDP = 45,
                            Weight = 0,
                            CoreNumber = 4,
                            ProcessorFamily = "Intel core 5",
                            Socket = 10,
                            Technology = 14,
                            ThreadNumber = 4
                        },
                        new
                        {
                            Id = new Guid("33000000-0000-0000-0000-000000000000"),
                            Available = 1,
                            Category = 0,
                            DateSinceInStore = new DateTime(2020, 4, 28, 10, 58, 34, 388, DateTimeKind.Local).AddTicks(4916),
                            Description = "Magok száma:24, Család:AMD Ryzen Threadripper, Processzor foglalat:AMD TR4, Órajel (Mhz):3000, VGA típus:Nem, Fogyasztás (W):250, L3 Cache (MB):64, Architektúra (bit):Zen+, Gyártási technológia (nm):12, Hűtőventilátor:Nem, L2 Cache (MB):12, Hűtőborda:Nem",
                            DiscountedPrice = 410000,
                            GamingFlag = false,
                            HasRGB = false,
                            HighlightedItem = false,
                            IsUsed = false,
                            Manufacturer = "AMD",
                            Name = "AMD Ryzen Threadripper 2970WX ",
                            OriginalPrice = 443390,
                            PicturePath = "33000000-0000-0000-0000-000000000000.jpg",
                            ShortDescription = "Felsőkategóriás processor, munkaállomásba",
                            Warranty = "3 years",
                            BaseClock = 3000,
                            TDP = 250,
                            Weight = 0,
                            CoreNumber = 24,
                            ProcessorFamily = "AMD threadripper",
                            Socket = 12,
                            Technology = 12,
                            ThreadNumber = 24
                        });
                });

            modelBuilder.Entity("WebShop.Dal.Models.GraphicsCard", b =>
                {
                    b.HasBaseType("WebShop.Dal.Models.Hardware");

                    b.Property<int>("BandWidth")
                        .HasColumnType("int");

                    b.Property<int>("BuiltInMemory")
                        .HasColumnType("int");

                    b.Property<string>("CoolerType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MemoryClock")
                        .HasColumnType("int");

                    b.Property<int>("MemoryType")
                        .HasColumnType("int");

                    b.Property<string>("PowerSupplyConnection")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("GraphicsCard");

                    b.HasData(
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000000"),
                            Available = 3,
                            Category = 1,
                            DateSinceInStore = new DateTime(2020, 4, 28, 10, 58, 34, 388, DateTimeKind.Local).AddTicks(7159),
                            Description = "Morbi efficitur iaculis luctus. Quisque efficitur magna nec sapien finibus euismod. Nullam suscipit enim id dui hendrerit imperdiet. Donec ultrices venenatis nisl, nec condimentum neque. Vivamus ut arcu tincidunt, dapibus nunc ut, vulputate arcu. Nulla molestie leo at quam laoreet, id consectetur augue facilisis. Mauris in eleifend purus, a suscipit risus.",
                            DiscountedPrice = 165000,
                            GamingFlag = true,
                            HasRGB = true,
                            HighlightedItem = true,
                            IsUsed = false,
                            Manufacturer = "Gigabyte",
                            Name = "Gigabyte RTX2070 Super 8GB GDDR6 GV-N207SGAMINGOC WHITE-8GD videokártya",
                            OriginalPrice = 216000,
                            PicturePath = "40000000-0000-0000-0000-000000000000.jpg",
                            ShortDescription = "High end gpu in amazing white color",
                            Warranty = "5 years",
                            BaseClock = 1770,
                            TDP = 215,
                            Weight = 0,
                            BandWidth = 256,
                            BuiltInMemory = 8192,
                            CoolerType = "Windforce 3x",
                            MemoryClock = 14000,
                            MemoryType = 7,
                            PowerSupplyConnection = "6 + 8"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000000"),
                            Available = 0,
                            Category = 1,
                            DateSinceInStore = new DateTime(2020, 5, 26, 10, 58, 34, 388, DateTimeKind.Local).AddTicks(7245),
                            Description = "Morbi efficitur iaculis luctus. Quisque efficitur magna nec sapien finibus euismod. Nullam suscipit enim id dui hendrerit imperdiet. Donec ultrices venenatis nisl, nec condimentum neque. Vivamus ut arcu tincidunt, dapibus nunc ut, vulputate arcu. Nulla molestie leo at quam laoreet, id consectetur augue facilisis. Mauris in eleifend purus, a suscipit risus.",
                            DiscountedPrice = 79900,
                            GamingFlag = false,
                            HasRGB = false,
                            HighlightedItem = false,
                            IsUsed = false,
                            Manufacturer = "MSI",
                            Name = "MSI Radeon RX 5500 XT MECH 8G OC videokártya",
                            OriginalPrice = 85500,
                            PicturePath = "50000000-0000-0000-0000-000000000000.jpg",
                            ShortDescription = "Low end basic graphics card for work",
                            Warranty = "3 years",
                            BaseClock = 1845,
                            TDP = 130,
                            Weight = 0,
                            BandWidth = 128,
                            BuiltInMemory = 8192,
                            CoolerType = "Active",
                            MemoryClock = 14000,
                            MemoryType = 7,
                            PowerSupplyConnection = "8"
                        },
                        new
                        {
                            Id = new Guid("55500000-0000-0000-0000-000000000000"),
                            Available = 15,
                            Category = 1,
                            DateSinceInStore = new DateTime(2020, 5, 26, 10, 58, 34, 388, DateTimeKind.Local).AddTicks(7253),
                            Description = "Új Turing GPU architektúra és Ray-tracing technológia: tükröződés és fejlettebb effektek valós időben. DirectX 12: fejlettebb vizualitás és optimalizált teljesítmény. Axial-tech fans: különleges és egyedi hűtés, halk és hatékony működés. Super Alloy Power II: elsőosztályú alkatrészekkel szerelve a hosszú élettartamért és a stabil energiaellátásért.MaxContact Technology: a hűtőborda hatékonyabb elhelyezésével nő a hővezetőképesség",
                            DiscountedPrice = 370000,
                            GamingFlag = false,
                            HasRGB = false,
                            HighlightedItem = true,
                            IsUsed = false,
                            Manufacturer = "MSI",
                            Name = "Asus RTX2080 Ti 11GB GDDR6 ROG-STRIX-RTX2080TI-O11G-GAMING",
                            OriginalPrice = 548590,
                            PicturePath = "55500000-0000-0000-0000-000000000000.jpg",
                            ShortDescription = "Best GPU money can buy",
                            Warranty = "3 years",
                            BaseClock = 1350,
                            TDP = 170,
                            Weight = 0,
                            BandWidth = 128,
                            BuiltInMemory = 11264,
                            CoolerType = "Active",
                            MemoryClock = 14000,
                            MemoryType = 7,
                            PowerSupplyConnection = "8 + 8"
                        });
                });

            modelBuilder.Entity("WebShop.Dal.Models.HardDrive", b =>
                {
                    b.HasBaseType("WebShop.Dal.Models.Hardware");

                    b.Property<int>("ReadSpeed")
                        .HasColumnType("int");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<int>("Socket")
                        .HasColumnName("HardDrive_Socket")
                        .HasColumnType("int");

                    b.Property<int>("WriteSpeed")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("HardDrive");

                    b.HasData(
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000000"),
                            Available = 20,
                            Category = 3,
                            DateSinceInStore = new DateTime(2020, 4, 28, 10, 58, 34, 388, DateTimeKind.Local).AddTicks(8829),
                            GamingFlag = false,
                            HasRGB = false,
                            HighlightedItem = false,
                            IsUsed = false,
                            Manufacturer = "Samsung",
                            Name = "Samsung 250GB 970 EVO Plus MZ-V7S250BW M.2 PCIe SSD meghajtó",
                            OriginalPrice = 28600,
                            PicturePath = "60000000-0000-0000-0000-000000000000.jpg",
                            ShortDescription = "Very fast SSD ",
                            Warranty = "5 years",
                            BaseClock = 0,
                            TDP = 0,
                            Weight = 0,
                            ReadSpeed = 3500,
                            Size = 250,
                            Socket = 2,
                            WriteSpeed = 2300
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000000"),
                            Available = 0,
                            Category = 3,
                            DateSinceInStore = new DateTime(2020, 4, 28, 10, 58, 34, 388, DateTimeKind.Local).AddTicks(8892),
                            Description = "A Kingston A400 egy 2,5\" -os SSD meghajtó, melynek kapacitása 240 GB és PC vagy notebook felhasználást képes teljesmértékben egy egy erőteljes géppé változtatni. A készülék frissítése még sosem volt egyszerűbb. Összehasonlítva a mechanikus merevlemezekkel azonnal észrevehető a teljesítmény növekedés. Már az indítás során észlelhetjük, hogy az operációs rendszer betöltése sokkal gyorsabb. Ésegyéb műveletek, mint az alkalmazások indítására, másolás vagy mozgó kép indítására sem kell már olyan sokáig várni, mint korábban",
                            GamingFlag = false,
                            HasRGB = false,
                            HighlightedItem = true,
                            IsUsed = false,
                            Manufacturer = "Kingston",
                            Name = "Kingston 240GB SA400S37/240G SSD meghajtó",
                            OriginalPrice = 14000,
                            PicturePath = "70000000-0000-0000-0000-000000000000.jpg",
                            ShortDescription = "Resonably fast SSD ",
                            Warranty = "5 years",
                            BaseClock = 0,
                            TDP = 0,
                            Weight = 0,
                            ReadSpeed = 500,
                            Size = 240,
                            Socket = 1,
                            WriteSpeed = 350
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000000"),
                            Available = 20,
                            Category = 3,
                            DateSinceInStore = new DateTime(2020, 5, 25, 10, 58, 34, 388, DateTimeKind.Local).AddTicks(8900),
                            Description = "Morbi efficitur iaculis luctus. Quisque efficitur magna nec sapien finibus euismod. Nullam suscipit enim id dui hendrerit imperdiet. Donec ultrices venenatis nisl, nec condimentum neque. Vivamus ut arcu tincidunt, dapibus nunc ut, vulputate arcu. Nulla molestie leo at quam laoreet, id consectetur augue facilisis. Mauris in eleifend purus, a suscipit risus.",
                            DiscountedPrice = 65000,
                            GamingFlag = false,
                            HasRGB = false,
                            HighlightedItem = false,
                            IsUsed = false,
                            Manufacturer = "Seagate",
                            Name = "Seagate SkyHawk Surveillance 10TB 7200rpm 256MB SATA3 3,5\" HDD",
                            OriginalPrice = 108000,
                            PicturePath = "80000000-0000-0000-0000-000000000000.jpg",
                            ShortDescription = "Biggest HDD you've ever seen",
                            Warranty = "5 years",
                            BaseClock = 0,
                            TDP = 0,
                            Weight = 0,
                            ReadSpeed = 50,
                            Size = 10000,
                            Socket = 0,
                            WriteSpeed = 35
                        });
                });

            modelBuilder.Entity("WebShop.Dal.Models.Memory", b =>
                {
                    b.HasBaseType("WebShop.Dal.Models.Hardware");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("Kit")
                        .HasColumnType("int");

                    b.Property<int>("MemoryType")
                        .HasColumnName("MemoryType1")
                        .HasColumnType("int");

                    b.Property<int>("Timing")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Memory");

                    b.HasData(
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000000"),
                            Available = 20,
                            Category = 4,
                            DateSinceInStore = new DateTime(2020, 4, 28, 10, 58, 34, 389, DateTimeKind.Local).AddTicks(451),
                            Description = "Morbi efficitur iaculis luctus. Quisque efficitur magna nec sapien finibus euismod. Nullam suscipit enim id dui hendrerit imperdiet. Donec ultrices venenatis nisl, nec condimentum neque. Vivamus ut arcu tincidunt, dapibus nunc ut, vulputate arcu. Nulla molestie leo at quam laoreet, id consectetur augue facilisis. Mauris in eleifend purus, a suscipit risus.",
                            DiscountedPrice = 34000,
                            GamingFlag = false,
                            HasRGB = false,
                            HighlightedItem = false,
                            IsUsed = false,
                            Manufacturer = "Kingston",
                            Name = "Kingston 2x8GB DDR4 3200MHz HyperX Predator XMP HX432C16PB3K2/16 memória",
                            OriginalPrice = 38000,
                            PicturePath = "90000000-0000-0000-0000-000000000000.jpg",
                            ShortDescription = "High end memory in amazing white color",
                            Warranty = "5 years",
                            BaseClock = 3200,
                            TDP = 0,
                            Weight = 0,
                            Capacity = 8,
                            Kit = 2,
                            MemoryType = 3,
                            Timing = 16
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Available = 20,
                            Category = 4,
                            DateSinceInStore = new DateTime(2020, 5, 23, 10, 58, 34, 389, DateTimeKind.Local).AddTicks(526),
                            Description = "Morbi efficitur iaculis luctus. Quisque efficitur magna nec sapien finibus euismod. Nullam suscipit enim id dui hendrerit imperdiet. Donec ultrices venenatis nisl, nec condimentum neque. Vivamus ut arcu tincidunt, dapibus nunc ut, vulputate arcu. Nulla molestie leo at quam laoreet, id consectetur augue facilisis. Mauris in eleifend purus, a suscipit risus.",
                            GamingFlag = true,
                            HasRGB = true,
                            HighlightedItem = true,
                            IsUsed = false,
                            Manufacturer = "Kingston",
                            Name = "Kingston 2x8GB DDR4 3200MHz HyperX Predator RGB HX432C16PB3AK2/16 memória",
                            OriginalPrice = 41000,
                            PicturePath = "10000000-0000-0000-0000-000000000001.jpg",
                            ShortDescription = "High end memory with inbuilt RGB for so many fps!!!",
                            Warranty = "5 years",
                            BaseClock = 3200,
                            TDP = 0,
                            Weight = 0,
                            Capacity = 8,
                            Kit = 2,
                            MemoryType = 3,
                            Timing = 16
                        });
                });

            modelBuilder.Entity("WebShop.Dal.Models.Motherboard", b =>
                {
                    b.HasBaseType("WebShop.Dal.Models.Hardware");

                    b.Property<string>("Chipset")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MemorySocketNumber")
                        .HasColumnType("int");

                    b.Property<int>("Socket")
                        .HasColumnName("Motherboard_Socket")
                        .HasColumnType("int");

                    b.Property<string>("SupportedMemorySpeed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SupportedMemoryType")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Motherboard");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11000000-0000-0000-0000-000000000000"),
                            Available = 20,
                            Category = 5,
                            DateSinceInStore = new DateTime(2020, 4, 28, 10, 58, 34, 389, DateTimeKind.Local).AddTicks(2686),
                            Description = "Morbi efficitur iaculis luctus. Quisque efficitur magna nec sapien finibus euismod. Nullam suscipit enim id dui hendrerit imperdiet. Donec ultrices venenatis nisl, nec condimentum neque. Vivamus ut arcu tincidunt, dapibus nunc ut, vulputate arcu. Nulla molestie leo at quam laoreet, id consectetur augue facilisis. Mauris in eleifend purus, a suscipit risus.",
                            DiscountedPrice = 48000,
                            GamingFlag = true,
                            HasRGB = true,
                            HighlightedItem = false,
                            IsUsed = false,
                            Manufacturer = "ASUS",
                            Name = "ASUS PRIME Z390-A alaplap",
                            OriginalPrice = 69000,
                            PicturePath = "11000000-0000-0000-0000-000000000000.jpg",
                            ShortDescription = "Great motherboard. Gets the job done",
                            Warranty = "20 years",
                            BaseClock = 0,
                            TDP = 0,
                            Weight = 0,
                            Chipset = "Z390",
                            MemorySocketNumber = 4,
                            Socket = 10,
                            SupportedMemorySpeed = "2133, 2400, 2666, 2800, 3000, 3200, 3300, 3333, 3400, 3466, 3600",
                            SupportedMemoryType = 3,
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("12000000-0000-0000-0000-000000000000"),
                            Available = 20,
                            Category = 5,
                            DateSinceInStore = new DateTime(2020, 4, 28, 10, 58, 34, 389, DateTimeKind.Local).AddTicks(2754),
                            Description = "Morbi efficitur iaculis luctus. Quisque efficitur magna nec sapien finibus euismod. Nullam suscipit enim id dui hendrerit imperdiet. Donec ultrices venenatis nisl, nec condimentum neque. Vivamus ut arcu tincidunt, dapibus nunc ut, vulputate arcu. Nulla molestie leo at quam laoreet, id consectetur augue facilisis. Mauris in eleifend purus, a suscipit risus.",
                            GamingFlag = false,
                            HasRGB = false,
                            HighlightedItem = false,
                            IsUsed = false,
                            Manufacturer = "Gigabyte",
                            Name = "Gigabyte GA-B365-D3H alaplap",
                            OriginalPrice = 35000,
                            PicturePath = "12000000-0000-0000-0000-000000000000.jpg",
                            ShortDescription = "Basic motherboard. No overclocking here",
                            Warranty = "2 years",
                            BaseClock = 0,
                            TDP = 0,
                            Weight = 0,
                            Chipset = "B365",
                            MemorySocketNumber = 0,
                            Socket = 3,
                            SupportedMemorySpeed = "2133, 2400, 2666",
                            SupportedMemoryType = 3,
                            Type = 2
                        });
                });

            modelBuilder.Entity("WebShop.Dal.Models.PowerSupply", b =>
                {
                    b.HasBaseType("WebShop.Dal.Models.Hardware");

                    b.Property<int>("ATXConnector")
                        .HasColumnType("int");

                    b.Property<int>("Efficiency")
                        .HasColumnType("int");

                    b.Property<bool>("IsModular")
                        .HasColumnType("bit");

                    b.Property<int>("MolexConnector")
                        .HasColumnType("int");

                    b.Property<int>("SixPinConnector")
                        .HasColumnType("int");

                    b.Property<int>("SixPlusTwoConnector")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("PowerSupply");

                    b.HasData(
                        new
                        {
                            Id = new Guid("13000000-0000-0000-0000-000000000000"),
                            Available = 20,
                            Category = 6,
                            DateSinceInStore = new DateTime(2020, 4, 28, 10, 58, 34, 389, DateTimeKind.Local).AddTicks(4943),
                            Description = "Morbi efficitur iaculis luctus. Quisque efficitur magna nec sapien finibus euismod. Nullam suscipit enim id dui hendrerit imperdiet. Donec ultrices venenatis nisl, nec condimentum neque. Vivamus ut arcu tincidunt, dapibus nunc ut, vulputate arcu. Nulla molestie leo at quam laoreet, id consectetur augue facilisis. Mauris in eleifend purus, a suscipit risus.",
                            GamingFlag = false,
                            HasRGB = false,
                            HighlightedItem = false,
                            IsUsed = false,
                            Manufacturer = "Chieftec",
                            Name = "Chieftec ECO 400W GPE-400S tápegység",
                            OriginalPrice = 13700,
                            PicturePath = "13000000-0000-0000-0000-000000000000.jpg",
                            ShortDescription = "Cheap psu, dont buy this",
                            Warranty = "3 years",
                            BaseClock = 0,
                            TDP = 0,
                            Weight = 0,
                            ATXConnector = 1,
                            Efficiency = 85,
                            IsModular = false,
                            MolexConnector = 2,
                            SixPinConnector = 0,
                            SixPlusTwoConnector = 0
                        },
                        new
                        {
                            Id = new Guid("14000000-0000-0000-0000-000000000000"),
                            Available = 0,
                            Category = 6,
                            DateSinceInStore = new DateTime(2020, 4, 28, 10, 58, 34, 389, DateTimeKind.Local).AddTicks(5013),
                            Description = "Morbi efficitur iaculis luctus. Quisque efficitur magna nec sapien finibus euismod. Nullam suscipit enim id dui hendrerit imperdiet. Donec ultrices venenatis nisl, nec condimentum neque. Vivamus ut arcu tincidunt, dapibus nunc ut, vulputate arcu. Nulla molestie leo at quam laoreet, id consectetur augue facilisis. Mauris in eleifend purus, a suscipit risus.",
                            DiscountedPrice = 25000,
                            GamingFlag = false,
                            HasRGB = false,
                            HighlightedItem = true,
                            IsUsed = false,
                            Manufacturer = "FSP",
                            Name = "FSP 650W Hyper M tápegység",
                            OriginalPrice = 29790,
                            PicturePath = "14000000-0000-0000-0000-000000000000.jpg",
                            ShortDescription = "You should by this not that chinesee crap",
                            Warranty = "3 years",
                            BaseClock = 0,
                            TDP = 0,
                            Weight = 0,
                            ATXConnector = 1,
                            Efficiency = 85,
                            IsModular = true,
                            MolexConnector = 3,
                            SixPinConnector = 0,
                            SixPlusTwoConnector = 4
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("WebShop.Dal.Models.WebShopUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("WebShop.Dal.Models.WebShopUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebShop.Dal.Models.WebShopUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("WebShop.Dal.Models.WebShopUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebShop.Dal.Models.Comment", b =>
                {
                    b.HasOne("WebShop.Dal.Models.Item", null)
                        .WithMany("Comments")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebShop.Dal.Models.WebShopUser", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebShop.Dal.Models.Order", b =>
                {
                    b.HasOne("WebShop.Dal.Models.WebShopUser", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("WebShop.Dal.Models.Address", "BillingAddress", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("HouseNumberAndDoor")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("OrderId");

                            b1.ToTable("Orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.OwnsOne("WebShop.Dal.Models.Address", "ShippingAddress", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("HouseNumberAndDoor")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("OrderId");

                            b1.ToTable("Orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });
                });

            modelBuilder.Entity("WebShop.Dal.Models.OrderItem", b =>
                {
                    b.HasOne("WebShop.Dal.Models.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebShop.Dal.Models.Rating", b =>
                {
                    b.HasOne("WebShop.Dal.Models.Item", null)
                        .WithMany("Ratings")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebShop.Dal.Models.WebShopUser", null)
                        .WithMany("Ratings")
                        .HasForeignKey("WebShopUserId");
                });

            modelBuilder.Entity("WebShop.Dal.Models.UserSubscription", b =>
                {
                    b.HasOne("WebShop.Dal.Models.WebShopUser", null)
                        .WithMany("Subscriptions")
                        .HasForeignKey("WebShopUserId");
                });

            modelBuilder.Entity("WebShop.Dal.Models.Users.UserCartItem", b =>
                {
                    b.HasOne("WebShop.Dal.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebShop.Dal.Models.WebShopUser", "User")
                        .WithMany("CartItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebShop.Dal.Models.WebShopUser", b =>
                {
                    b.OwnsOne("WebShop.Dal.Models.Address", "BillingAddress", b1 =>
                        {
                            b1.Property<Guid>("WebShopUserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("HouseNumberAndDoor")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("WebShopUserId");

                            b1.ToTable("AspNetUsers");

                            b1.WithOwner()
                                .HasForeignKey("WebShopUserId");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
